import jsPDF from 'jspdf';
import { CycleRecord, DailyLog, CycleEngine, FLOW_LABELS } from './cycleEngine';
import { format } from 'date-fns';

export function generateDoctorReport(params: {
    userName: string;
    cycles: CycleRecord[];
    logs: DailyLog[];
    profile: {
        averageCycleLength: number;
        averagePeriodLength: number;
        hasPcos: boolean;
        hasEndometriosis: boolean;
        isIrregular: boolean;
        dateOfBirth: string;
    };
}) {
    const { userName, cycles, logs, profile } = params;
    const doc = new jsPDF();
    const prediction = CycleEngine.predict(cycles, logs);

    let y = 20;
    const leftMargin = 20;
    const lineHeight = 7;

    // Header
    doc.setFontSize(20);
    doc.setFont('helvetica', 'bold');
    doc.text('Menstrual Health Report', leftMargin, y);
    y += lineHeight + 3;

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(100);
    doc.text(
        `Generated by Vihaan · ${format(new Date(), 'MMMM d, yyyy')}`,
        leftMargin,
        y
    );
    doc.text(
        'For discussion with your healthcare provider. Not a medical document.',
        leftMargin,
        y + 5
    );
    y += lineHeight + 10;

    // Divider
    doc.setDrawColor(220, 200, 200);
    doc.line(leftMargin, y, 190, y);
    y += 8;

    // Patient Info
    doc.setFontSize(13);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(40);
    doc.text('Patient Information', leftMargin, y);
    y += lineHeight;

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(`Name: ${userName}`, leftMargin, y);
    y += lineHeight;
    if (profile.dateOfBirth) {
        doc.text(`Date of Birth: ${profile.dateOfBirth}`, leftMargin, y);
        y += lineHeight;
    }
    doc.text(
        `Report Date: ${format(new Date(), 'MMMM d, yyyy')}`,
        leftMargin,
        y
    );
    y += lineHeight;

    const conditions: string[] = [];
    if (profile.hasPcos) conditions.push('PCOS');
    if (profile.hasEndometriosis) conditions.push('Endometriosis');
    if (profile.isIrregular) conditions.push('Irregular cycles');
    if (conditions.length > 0) {
        doc.text(
            `Reported Conditions: ${conditions.join(', ')}`,
            leftMargin,
            y
        );
        y += lineHeight;
    }
    y += 5;

    // Cycle Summary
    doc.setFontSize(13);
    doc.setFont('helvetica', 'bold');
    doc.text('Cycle Summary', leftMargin, y);
    y += lineHeight;

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(`Total cycles tracked: ${cycles.length}`, leftMargin, y);
    y += lineHeight;
    doc.text(
        `Average cycle length: ${profile.averageCycleLength} days`,
        leftMargin,
        y
    );
    y += lineHeight;
    doc.text(
        `Average period length: ${profile.averagePeriodLength} days`,
        leftMargin,
        y
    );
    y += lineHeight;
    doc.text(`Prediction confidence: ${prediction.confidence}`, leftMargin, y);
    y += lineHeight;
    doc.text(
        `Next period predicted: ${prediction.nextPeriodStart}`,
        leftMargin,
        y
    );
    y += lineHeight;
    y += 5;

    // Cycle History Table
    if (cycles.length > 0) {
        doc.setFontSize(13);
        doc.setFont('helvetica', 'bold');
        doc.text('Cycle History', leftMargin, y);
        y += lineHeight;

        doc.setFontSize(9);
        doc.setFont('helvetica', 'bold');
        doc.text('Start Date', leftMargin, y);
        doc.text('Length (days)', 80, y);
        doc.text('Period Length', 130, y);
        y += lineHeight - 2;
        doc.setFont('helvetica', 'normal');

        cycles.slice(-6).forEach((cycle) => {
            if (y > 270) {
                doc.addPage();
                y = 20;
            }
            doc.text(cycle.startDate, leftMargin, y);
            doc.text(cycle.length?.toString() ?? '—', 80, y);
            doc.text(cycle.periodLength?.toString() ?? '—', 130, y);
            y += lineHeight - 1;
        });
        y += 5;
    }

    // Symptom frequency
    const symptomCounts: Record<string, number> = {};
    logs.forEach((log) => {
        log.symptoms.forEach((s) => {
            if (s !== 'None') symptomCounts[s] = (symptomCounts[s] || 0) + 1;
        });
    });

    const topSymptoms = Object.entries(symptomCounts)
        .sort((a, b) => b[1] - a[1])
        .slice(0, 8);

    if (topSymptoms.length > 0) {
        if (y > 240) {
            doc.addPage();
            y = 20;
        }
        doc.setFontSize(13);
        doc.setFont('helvetica', 'bold');
        doc.text('Symptom Frequency', leftMargin, y);
        y += lineHeight;

        doc.setFontSize(10);
        doc.setFont('helvetica', 'normal');
        topSymptoms.forEach(([symptom, count]) => {
            doc.text(
                `${symptom}: ${count} occurrence${count > 1 ? 's' : ''} across ${logs.length} logged days`,
                leftMargin,
                y
            );
            y += lineHeight - 1;
        });
        y += 5;
    }

    // Recent Mood & Energy
    const recentLogs = logs.slice(-14);
    if (recentLogs.length > 0) {
        if (y > 230) {
            doc.addPage();
            y = 20;
        }
        doc.setFontSize(13);
        doc.setFont('helvetica', 'bold');
        doc.text('Recent 14-Day Log Summary', leftMargin, y);
        y += lineHeight;

        const energyLogs = recentLogs.filter((l) => l.energy > 0);
        const avgEnergy =
            energyLogs.length > 0
                ? energyLogs.reduce((sum, l) => sum + l.energy, 0) / energyLogs.length
                : NaN;

        const moodCounts: Record<string, number> = {};
        recentLogs.forEach((l) => {
            if (l.mood) moodCounts[l.mood] = (moodCounts[l.mood] || 0) + 1;
        });
        const topMood = Object.entries(moodCounts).sort(
            (a, b) => b[1] - a[1]
        )[0];

        doc.setFontSize(10);
        doc.setFont('helvetica', 'normal');
        if (!isNaN(avgEnergy)) {
            doc.text(
                `Average energy score: ${avgEnergy.toFixed(1)}/10`,
                leftMargin,
                y
            );
            y += lineHeight;
        }
        if (topMood) {
            doc.text(
                `Most frequent mood: ${topMood[0]} (${topMood[1]} times)`,
                leftMargin,
                y
            );
            y += lineHeight;
        }
        y += 5;
    }

    // Disclaimer footer
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text(
        'This report is generated from self-reported data in the Vihaan app. It is intended as a conversation starter',
        leftMargin,
        280
    );
    doc.text(
        'with your healthcare provider and does not constitute medical advice or diagnosis.',
        leftMargin,
        285
    );

    doc.save(`Vihaan_Health_Report_${format(new Date(), 'yyyy-MM-dd')}.pdf`);
}
